# -*- coding: UTF-8 -*-
from lemmes import Lemmatizer
import logging


# logging.basicConfig(level=logging.INFO)
if __name__ == '__main__':
    L = Lemmatizer()
    p = [
        u'autómata',
        u'autoriza',
        u'tenáculos',
        u'incesantemente',
        u'tempranisimo',
        u'varios',
        u'riquísimo',
        u'rodar',
        u'capitán',
        u'rodando',
        u'generando',
        u'suspendieron',
        u'años',
        u'anos',
        u'poniendo',
        u'ponerse',
        u'jamás',
        u'veces',
        u'mirando',
        u'mirandome',
        u'ojos',
        u'mujeres',
        u'hombres',
        u'varones',
        u'necesito',
        u'acaban',
        u'ponía',
        u'mentiría',
        u'sabiendo',
        u'sabiendas',
        u'saberes',
        u'muchosidad',
        u'morando',
        u'variamente',
        u'cardumenes',
        u'aerolíneas',
        u'desaparece',
        u'desapareciendo',
        u'amorios',
        u'circunstancialmente',
        u'moriría',
        u'muriendote',
        u'muriendonos',
        u'muriendome',
        u'muertes',
        u'morís',
        u'rajá',
        u'gracias',
        u'muere',
        u'partidos',
        u'aparecido',
        u'participando',
        u'participar',
        u'mantuvieron',
        u'ejecutados',
        u'sobrado',
        u'suscritos',
        u'querida',
        u'retrasando',
        u'deseoso',
        u'deseandote',
        u'miranda',
        u'mandan',
        u'cabida',
        u'miraditas',
        u'ansioso',
        u'periscópico',
        u'variando',
        u'últimamente',
        u'pudieramos',
        u'pudientemente',
        u'tenerte',
        u'totalmente',
        u'sexualizar',
        u'terminando',
        u'hablando',
        u'determinantemente',
        u'superandolos',
        u'superandote',
        u'superandose',
        u'superarse',
        u'superarse',
        u'extrañan',
        u'extrañandote',
        u'extraño',
        u'extrañarse',
        u'mutuamente',
        u'extrañesa',
        u'segregación',
        u'educativa',
        u'analizándote',
        u'analizándome',
        u'debidamente',
        u'debidamente',
        u'descentralizado',
        u'intentar',
        u'consideró',
        u'faltamiento',
        u'antiguamente',
        u'creía',
        u'creaba',
        u'señalan',
    ]

    for w in p:
        print repr(L.lemmatize(w))
